version: '3'
services:
  b-c01:
    container_name: b-c01
    hostname: b-c01
    build:
      context: ./Docker_build/Rocky8_container
      dockerfile: Dockerfile
    tty: true
    cap_add:
      - AUDIT_CONTROL  
      - AUDIT_READ
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
    tmpfs:
      - /run
    networks:
      b-rocky8_net:
        ipv4_address: 172.20.6.10
    extra_hosts:
      - "b-c02:172.20.6.11"
    ports:
      - "0.0.0.0:8221:80"
  b-c02:
    container_name: b-c02
    hostname: b-c02
    privileged: true
    build:
      context: ./Docker_build/Rocky8_container
      dockerfile: Dockerfile
    tty: true
    cap_add:
      - AUDIT_CONTROL  
      - AUDIT_READ
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
    tmpfs:
      - /run
    ulimits:
      nofile:
        soft: 5120
        hard: 5120
    networks:
      b-rocky8_net:
        ipv4_address: 172.20.6.11
    extra_hosts:
      - "b-c01:172.20.6.10"
networks:
  b-rocky8_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.6.0/24"

